const placeholderPages = [
  {
    section: "Workshops",
    title: "To be announced",
    url: "/workshops/to-be-announced/",
    summary: "Information about DSN 2027 workshops will be announced here.",
  },
  { section: "Awards", title: "Awards", url: "/awards/" },
  { section: "Awards", title: "Awards Information", url: "/awards/information/" },
  { section: "Awards", title: "Carter Award", url: "/awards/carter-award/" },
  { section: "Awards", title: "Rising Star Award", url: "/awards/rising-star-award/" },
  { section: "Awards", title: "Test of Time Award", url: "/awards/test-of-time-award/" },
  { section: "Awards", title: "Distinguished Artifact Award", url: "/awards/distinguished-artifact-award/" },
  { section: "Awards", title: "Jean-Claude Laprie Award", url: "/awards/jean-claude-laprie-award/" },
  { section: "Mentoring", title: "Mentoring", url: "/mentoring/" },
  { section: "Travel Grants", title: "Travel Grants", url: "/travel-grants/" },
  { section: "Travel Grants", title: "Student", url: "/travel-grants/student/" },
  { section: "Attend", title: "Attend", url: "/attend/" },
  { section: "Attend", title: "Venue", url: "/attend/venue/" },
  { section: "Attend", title: "Registration", url: "/attend/registration/" },
  { section: "Attend", title: "Visas and Invitation", url: "/attend/visas-and-invitation/" },
  { section: "Attend", title: "Accommodation", url: "/attend/accommodation/" },
  { section: "Attend", title: "Local Attractions", url: "/attend/local-attractions/" },
  { section: "Conference Program", title: "Program at a Glance", url: "/conference-program/program-at-a-glance/" },
  { section: "Conference Program", title: "Keynotes", url: "/conference-program/keynotes/" },
  { section: "Conference Program", title: "Accepted Papers", url: "/conference-program/accepted-papers/" },
  { section: "Conference Program", title: "Tutorials", url: "/conference-program/tutorials/" },
  { section: "Conference Program", title: "Research Artifacts", url: "/conference-program/research-artifacts/" },
  { section: "Conference Program", title: "Welcome Reception", url: "/conference-program/welcome-reception/" },
  { section: "Conference Program", title: "Excursion and Banquet", url: "/conference-program/excursion-and-banquet/" },
];

export default {
  items: [
    { title: "Home", url: "/" },
    { title: "Call for Contributions", url: "/call-for-contributions/" },
    {
      title: "Workshops",
      url: "/workshops/",
      activeUrls: ["/workshops/", "/workshops/to-be-announced/"],
      children: [{ title: "To be announced", url: "/workshops/to-be-announced/" }],
    },
    { title: "Committees", url: "/committees/" },
    {
      title: "Awards",
      url: "/awards/",
      activePrefix: "/awards/",
      children: [
        { title: "Awards Information", url: "/awards/information/" },
        { title: "Carter Award", url: "/awards/carter-award/" },
        { title: "Rising Star Award", url: "/awards/rising-star-award/" },
        { title: "Test of Time Award", url: "/awards/test-of-time-award/" },
        { title: "Distinguished Artifact Award", url: "/awards/distinguished-artifact-award/" },
        { title: "Jean-Claude Laprie Award", url: "/awards/jean-claude-laprie-award/" },
      ],
    },
    { title: "Mentoring", url: "/mentoring/" },
    {
      title: "Travel Grants",
      url: "/travel-grants/",
      activePrefix: "/travel-grants/",
      children: [{ title: "Student", url: "/travel-grants/student/" }],
    },
    {
      title: "Attend",
      url: "/attend/",
      activePrefix: "/attend/",
      children: [
        { title: "Venue", url: "/attend/venue/" },
        { title: "Registration", url: "/attend/registration/" },
        { title: "Visas and Invitation", url: "/attend/visas-and-invitation/" },
        { title: "Accommodation", url: "/attend/accommodation/" },
        { title: "Local Attractions", url: "/attend/local-attractions/" },
      ],
    },
    {
      title: "Conference Program",
      url: "/conference-program/",
      activePrefix: "/conference-program/",
      children: [
        { title: "Program at a Glance", url: "/conference-program/program-at-a-glance/" },
        { title: "Keynotes", url: "/conference-program/keynotes/" },
        { title: "Accepted Papers", url: "/conference-program/accepted-papers/" },
        { title: "Tutorials", url: "/conference-program/tutorials/" },
        { title: "Research Artifacts", url: "/conference-program/research-artifacts/" },
        { title: "Welcome Reception", url: "/conference-program/welcome-reception/" },
        { title: "Excursion and Banquet", url: "/conference-program/excursion-and-banquet/" },
      ],
    },
    { title: "Sponsors", url: "/sponsors/" },
    { title: "Previous DSN Conferences", url: "/previous-conferences/" },
  ],
  placeholderPages,
};
